commandlinefu_id: 13419
translator:
  weibo: ''
hide: true
command: |-
  awk '$1=="Host"{$1="";H=substr($0,2)};$1=="HostName"{print H,"$",$2}' ~/.ssh/config | column -s '$' -t
summary: |-
  Extract shortcuts and hostnames from .ssh/config
