commandlinefu_id: 3453
translator:
  weibo: Spacewander__罗泽轩
command: |-
  diff <(ssh server01 'cd config; find . -type f -exec md5sum {} \;| sort -k 2') <(ssh server02 'cd config;find . -type f -exec md5sum {} \;| sort -k 2')
summary: |-
  显示位于不同的服务器的文件夹的之间的差异
