commandlinefu_id: 12203
translator:
  weibo: ''
hide: true
command: |-
  echo 'Etc/UTC' | tee /etc/timezone; dpkg-reconfigure --frontend noninteractive tzdata
summary: |-
  Non-interactively set timezone in Ubuntu
