commandlinefu_id: 4247
translator:
  weibo: ''
hide: true
command: |-
  MyIps(){ echo -e "local:\n$(ifconfig $1 | grep -oP 'inet (add?r:)?\K(\d{1,3}\.){3}\d{1,3}')\n\npublic:\n$(curl -s sputnick-area.net/ip)"; }
summary: |-
  Show local/public IP adresses with or without interface argument using a shell function for Linux and MacOsX
