commandlinefu_id: 13524
translator:
  weibo: ''
hide: true
command: |-
  sudo ln -s /Applications/MAMP/tmp/mysql/mysql.sock /tmp/mysql.sock
summary: |-
  MAMP: "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)" solution
